server:
  port: 8089


spring:
  jackson:
    time-zone: Asia/Seoul

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: 
    username: 
    password: 

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update


jwt:
  secretKey: 
